"""Simulation adapters for offline testing.

These fake clients mimic the external services used by the pipeline so we can
exercise the workflow without network calls or API keys.
"""

from typing import Any, List


class FakeGeminiResponse:
    def __init__(self, text: str):
        self.text = text


class FakeGeminiModel:
    def __init__(self, model_name: str):
        self.model_name = model_name

    def generate_content(self, prompt: str, generation_config: Any = None) -> FakeGeminiResponse:
        if "OUTLINE_JSON" in prompt:
            return FakeGeminiResponse(
                "# FAKE SCRIPT\n\n[SCENE START]\n\nNarrator: This is a simulated script generated by the fake adapter.\n\n"
                "[B-ROLL: Cybernetic visual]\n\nNarrator: It works without an internet connection.\n"
            )
        if "threat-to-outline" in prompt or "Paradigm" in prompt:
            return FakeGeminiResponse(
                "```json\n{\n  \"title\": \"Simulated Campaign\",\n  \"chapters\": [\n    {\n      \"id\": \"chapter_1\",\n      \"title\": \"Chapter 1: The Simulation\",\n      \"scenes\": [\n        {\n          \"id\": \"scene_1\",\n          \"description\": \"A computer screen showing code.\"\n        }\n      ]\n    }\n  ]\n}\n```"
            )
        if "script-to-shorts" in prompt:
            return FakeGeminiResponse(
                "# Short 1\n\nNarrator: This is a simulated short.\n\n# Short 2\n\nNarrator: Another simulated short."
            )
        if "script-to-shotlist" in prompt or "TARGET_ASPECT_RATIO" in prompt:
            return FakeGeminiResponse(
                "```json\n{\n  \"scenes\": [\n    {\n      \"id\": \"scene_001\",\n      \"description\": \"Opening shot\",\n      \"sora_prompt\": \"Cinematic shot of a computer terminal, 8k\",\n      \"duration_seconds\": 5\n    }\n  ]\n}\n```"
            )
        return FakeGeminiResponse("This is generic simulated content from Gemini.")


class FakeGeminiAdapter:
    """Mimics the google.generativeai module shape used by scripts."""

    def __init__(self):
        self.GenerationConfig = self._FakeGenerationConfig
        self.GenerativeModel = FakeGeminiModel

    def configure(self, api_key: str):
        return None

    class _FakeGenerationConfig:
        def __init__(self, temperature=0.7, top_p=0.9, response_mime_type=None, max_output_tokens=None):
            self.temperature = temperature
            self.top_p = top_p
            self.response_mime_type = response_mime_type
            self.max_output_tokens = max_output_tokens


class FakeElevenLabsClient:
    """Lightweight stand-in for ElevenLabs client."""

    def __init__(self, api_key: str | None = None):
        self.text_to_speech = self.TextToSpeech()

    class TextToSpeech:
        def convert(self, voice_id: str, text: str, model_id: str) -> List[bytes]:
            return [b"FAKE_AUDIO_DATA_" * 10]


class FakeOpenAIResponse:
    def __init__(self, id: str, status: str, output: List[Any]):
        self.id = id
        self.status = status
        self.output = output


class FakeOpenAIOutput:
    def __init__(self, url: str):
        self.url = url


class FakeOpenAIClient:
    """Simple mock for openai.OpenAI responses client."""

    def __init__(self, api_key: str | None = None):
        self.responses = self.Responses()

    class Responses:
        def create(self, model: str, input: str, n: int, size: str, duration: int) -> FakeOpenAIResponse:
            return FakeOpenAIResponse(id="fake_job_id_123", status="processing", output=[])

        def retrieve(self, id: str) -> FakeOpenAIResponse:
            return FakeOpenAIResponse(id=id, status="completed", output=[FakeOpenAIOutput(url="http://fake-url/video.mp4")])


def get_fake_httpx_client():
    class _FakeResponse:
        content = b"FAKE_VIDEO_DATA"

    class _FakeHttpxClient:
        def __enter__(self):
            return self

        def __exit__(self, exc_type, exc_val, exc_tb):
            return None

        def get(self, url):
            return _FakeResponse()

    return _FakeHttpxClient
