"""
Simulation adapters for the Shai-Hulud pipeline.
These classes mimic the behavior of real API clients for testing and simulation purposes.
"""

from typing import Any, List
from pathlib import Path

class FakeGeminiResponse:
    def __init__(self, text: str):
        self.text = text

class FakeGeminiModel:
    def __init__(self, model_name: str):
        self.model_name = model_name

    def generate_content(self, prompt: str, generation_config: Any = None) -> FakeGeminiResponse:
        # Generate obviously fake content based on the prompt
        if "OUTLINE_JSON" in prompt:
            # Script generation
            return FakeGeminiResponse(
                "# FAKE SCRIPT\n\n[SCENE START]\n\nNarrator: This is a simulated script generated by the fake adapter.\n\n[B-ROLL: Cybernetic visual]\n\nNarrator: It works without an internet connection.\n"
            )
        elif "threat-to-outline" in prompt or "Paradigm" in prompt:
             # Outline generation
             return FakeGeminiResponse(
                 '```json\n{\n  "title": "Simulated Campaign",\n  "chapters": [\n    {\n      "title": "Chapter 1: The Simulation",\n      "scenes": [\n        {"description": "A computer screen showing code."}\n      ]\n    }\n  ]\n}\n```'
             )
        elif "script-to-shorts" in prompt:
            # Shorts generation
            return FakeGeminiResponse(
                "# Short 1\n\nNarrator: This is a simulated short.\n\n# Short 2\n\nNarrator: Another simulated short."
            )
        elif "script-to-shotlist" in prompt or "TARGET_ASPECT_RATIO" in prompt:
            # Shotlist generation
            return FakeGeminiResponse(
                '```json\n{\n  "scenes": [\n    {\n      "id": "scene_001",\n      "description": "Opening shot",\n      "sora_prompt": "Cinematic shot of a computer terminal, 8k",\n      "duration_seconds": 5\n    }\n  ]\n}\n```'
            )
        else:
            return FakeGeminiResponse("This is generic simulated content from Gemini.")

class FakeGeminiAdapter:
    """Mimics google.generativeai module structure needed by the scripts."""

    def __init__(self):
        self.GenerationConfig = self._fake_generation_config
        self.GenerativeModel = FakeGeminiModel

    def configure(self, api_key: str):
        pass

    class _fake_generation_config:
        def __init__(self, temperature=0.7, max_output_tokens=1000, response_mime_type=None):
            pass

class FakeElevenLabsClient:
    """Mimics elevenlabs.ElevenLabs client."""
    def __init__(self, api_key: str = None):
        self.text_to_speech = self.TextToSpeech()

    class TextToSpeech:
        def convert(self, voice_id: str, text: str, model_id: str) -> List[bytes]:
            # Return some fake audio bytes (silence or just patterns)
            # 1 second of silence at 44.1kHz 16-bit mono is 88200 bytes
            # We'll just return a small buffer to indicate "audio"
            return [b"FAKE_AUDIO_DATA_" * 10]

class FakeOpenAIResponse:
    def __init__(self, id: str, status: str, output: List[Any]):
        self.id = id
        self.status = status
        self.output = output

class FakeOpenAIOutput:
    def __init__(self, url: str):
        self.url = url

class FakeOpenAIClient:
    """Mimics openai.OpenAI client."""
    def __init__(self, api_key: str = None):
        self.responses = self.Responses()

    class Responses:
        def create(self, model: str, input: str, n: int, size: str, duration: int) -> FakeOpenAIResponse:
            return FakeOpenAIResponse(
                id="fake_job_id_123",
                status="processing",
                output=[]
            )

        def retrieve(self, id: str) -> FakeOpenAIResponse:
            # Always return completed for simulation
            return FakeOpenAIResponse(
                id=id,
                status="completed",
                output=[FakeOpenAIOutput(url="http://fake-url/video.mp4")]
            )

# Helpers to patch the libraries in the scripts
def get_fake_httpx_client():
    class FakeResponse:
        content = b"FAKE_VIDEO_DATA"

    class FakeHttpxClient:
        def __enter__(self): return self
        def __exit__(self, exc_type, exc_val, exc_tb): pass
        def get(self, url): return FakeResponse()

    return FakeHttpxClient
